version: "3"
services:
  web1:
    image: httpd:2.4.43
    ports:
      - "8080:80"
    volumes:
       - /docker/nginx/v1:/usr/local/apache2/htdocs/


  web2:
    image: httpd:2.4.43
    ports:
      - "8081:80"
    volumes:
       - /docker/nginx/v2:/usr/local/apache2/htdocs/

  nginx2:
    image: nginx:1.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /docker/nginx/nginx:/etc/nginx/conf.d
       - /docker/nginx/log:/var/log/nginx
